[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
]

[profile.default.optimizer]
enabled = true
runs = 200

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
